//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package developer

// DPGClientBeginLroOptions contains the optional parameters for the DPGClient.BeginLro method.
type DPGClientBeginLroOptions struct {
	// Resumes the LRO from the provided token.
	ResumeToken string
}

// DPGClientGetModelOptions contains the optional parameters for the DPGClient.GetModel method.
type DPGClientGetModelOptions struct {
	// placeholder for future optional parameters
}

// DPGClientGetPagesOptions contains the optional parameters for the DPGClient.GetPages method.
type DPGClientGetPagesOptions struct {
	// placeholder for future optional parameters
}

// DPGClientPostModelOptions contains the optional parameters for the DPGClient.PostModel method.
type DPGClientPostModelOptions struct {
	// placeholder for future optional parameters
}

type Input struct {
	// REQUIRED
	Hello *string `json:"hello,omitempty"`
}

type LROProduct struct {
	// REQUIRED
	ProvisioningState *string `json:"provisioningState,omitempty"`

	// REQUIRED
	Received *ProductReceived `json:"received,omitempty"`
}

type Product struct {
	// REQUIRED
	Received *ProductReceived `json:"received,omitempty"`
}

type ProductResult struct {
	NextLink *string `json:"nextLink,omitempty"`
	Values []*Product `json:"values,omitempty"`
}

