//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package update

// ParamsClientDeleteParametersResponse contains the response from method ParamsClient.DeleteParameters.
type ParamsClientDeleteParametersResponse struct {
	// placeholder for future response values
}

// ParamsClientGetNewOperationResponse contains the response from method ParamsClient.GetNewOperation.
type ParamsClientGetNewOperationResponse struct {
	// Anything
	Interface interface{}
}

// ParamsClientGetOptionalResponse contains the response from method ParamsClient.GetOptional.
type ParamsClientGetOptionalResponse struct {
	// Anything
	Interface interface{}
}

// ParamsClientGetRequiredResponse contains the response from method ParamsClient.GetRequired.
type ParamsClientGetRequiredResponse struct {
	// Anything
	Interface interface{}
}

// ParamsClientHeadNoParamsResponse contains the response from method ParamsClient.HeadNoParams.
type ParamsClientHeadNoParamsResponse struct {
	// Anything
	Interface interface{}
}

// ParamsClientPostParametersResponse contains the response from method ParamsClient.PostParameters.
type ParamsClientPostParametersResponse struct {
	// Anything
	Interface interface{}
}

// ParamsClientPostParametersWithJSONResponse contains the response from method ParamsClient.PostParametersWithJSON.
type ParamsClientPostParametersWithJSONResponse struct {
	// Anything
	Interface interface{}
}

// ParamsClientPutRequiredOptionalResponse contains the response from method ParamsClient.PutRequiredOptional.
type ParamsClientPutRequiredOptionalResponse struct {
	// Anything
	Interface interface{}
}

