//go:build go1.18
// +build go1.18

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package developer

const host = "http://localhost:3000"

type ProductReceived string

const (
	ProductReceivedModel ProductReceived = "model"
	ProductReceivedRaw ProductReceived = "raw"
)

// PossibleProductReceivedValues returns the possible values for the ProductReceived const type.
func PossibleProductReceivedValues() []ProductReceived {
	return []ProductReceived{	
		ProductReceivedModel,
		ProductReceivedRaw,
	}
}

